Database:
  Host: localhost
  Port: 3310
  Username: root
  Password: minecraft
  Database: minigame

Module:
  Lobby-Selector: true
  Player-Options: true
  Rank-Upgrade: true
  PVP: true

Settings:
  Topup-Multipier: 1.0
